---
- name: Check if node_exporter binary already exists
  ansible.builtin.stat:
    path: /usr/bin/node_exporter
  register: node_exporter_binary

- name: Ensure node_exporter user exists
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: /bin/false
    create_home: false

- name: Download node_exporter archive
  ansible.builtin.get_url:
    url: >-
      https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version
      }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    mode: '0644'
  when: not node_exporter_binary.stat.exists

- name: Extract node_exporter archive
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: /tmp/
    remote_src: true
  when: not node_exporter_binary.stat.exists

- name: Move node_exporter binary to /usr/bin/node_exporter
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    remote_src: true
  when: not node_exporter_binary.stat.exists

- name: Remove extracted node_exporter directory
  ansible.builtin.file:
    path: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64"
    state: absent
  when: node_exporter_binary.stat.exists
  changed_when: false

- name: Deploy systemd unit for node_exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'
  notify: Reload systemd

- name: Ensure node_exporter is enabled and running
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
