---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: default
platforms:
  - name: instance
    template: "{{ lookup('env', 'TEMPLATE_NAME') }}"
    template_id: "{{ lookup('env', 'TEMPLATE_ID') }}"
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
  connection_options:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
