---
- name: Create /etc/nginx directory
  ansible.builtin.file:
    path: /etc/nginx
    state: directory
    mode: '0755'

- name: Copy nginx.conf file
  ansible.builtin.template:
    src: nginx.j2
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
